FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src/rpc
COPY ./rpc ./
WORKDIR /src/common
COPY ./common ./
WORKDIR /src/stats
COPY ./stats/TimeKeep.Stats.csproj .
RUN dotnet restore
COPY ./stats .
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY ./stats/appsettings.json .
COPY --from=publish /app/publish .
ENTRYPOINT dotnet TimeKeep.Stats.dll
