name: .NET Core Android

on:
  push:
    paths:
      - "app/**/*"

jobs:

  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
      
    - name: Install Workloads
      run: dotnet workload restore

    - name: Setup Android SDK 27, 28, 29 and 30
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9123335
    - run: sdkmanager tools "platforms;android-27" "platforms;android-28" "platforms;android-29" "platforms;android-30"

    - name: Publish Android App
      run: dotnet publish ./app/TimeKeep.App.Android/TimeKeep.App.Android.csproj -c Release -r android-arm64 --sc -o ./Output

    - name: Release Android App
      uses: softprops/action-gh-release@v1
      with:
        name: Android App
        files: ./Output/net.xn__sberg_lra.timekeep-Signed.apk
        draft: true
